server:
  applicationConnectors:
    - type: http
      port: 9000
  adminConnectors:
    - type: http
      port: 9001

# Database details
database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: tasker
  password: 123
  url: jdbc:mysql://taskerdb/tasker
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.show_sql: true
    hibernate.hbm2ddl.auto: update
    hibernate.cache.use_second_level_cache: false
    maxWaitForConnection: 1s
    validationQuery: "/* MyService Health Check */ SELECT 1"
    minSize: 8
    maxSize: 32
    checkConnectionWhileIdle: false